language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "4"
  - "5"
sudo: false
compiler: clang-3.6
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm install -g npm@latest
script: npm run-script coverage
