language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "4"
  - "5"
# SIGH need sudo for APT installs, for now
sudo: true
compiler: clang-3.6
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - sudo apt-get install atomicparsley
  - sudo apt-get install eyed3
  - npm install -g npm@latest
  - eyeD3 --help
  - eyeD3 --longhelp
script: npm run-script coverage
